Repository mbrobbel/dqcsim, pull requests merged in 2019-12, with the labels that each got.

#320 Clean up documentation generation
  .travis.yml
  doc/.gitignore
  doc/Makefile
  doc/README.md
  doc/book.toml
  doc/src/python-api/index.md
  doc/src/python-api/reference.md
  doc/src/python-api/sending-gates.md
  doc/src/python-api/simulations.md
  doc/src/rust-api/index.md
Labels: ci, documentation, enhancement

#322 Fix R gate in Python
  python/dqcsim/plugin/__init__.py
  python/dqcsim/tests/test_gate.py
Labels: bug, lang:python

#324 Add codecov.yml
  codecov.yml
Labels: ci

#332 Fix incorrect terminology in documentation
  doc/src/c-api/gate.apisrc.md
  doc/src/intro/gatestream.md
  doc/src/intro/operator.md
Labels: documentation

#353 Update crossbeam-channel and ipc-channel
  Cargo.lock
  rust/Cargo.toml
Labels: dependencies
